POST {{base-url}}/api/v1/adv-messages
Content-Type: application/json

{
  "CreationDateStart": "2019-03-01",
  "CreationDateEnd": "2019-03-30",
  "Advertisers": [],
  "Aspects": [],
  "AdvertisingMessageIDs": []
}

###
