POST {{base-url}}/api/v1/channels
Content-Type: application/json

{
  "SellingDirectionID": "23"
}

###

POST {{base-url}}/api/v1/channels/query
Content-Type: application/json

{
  "ShortName": {
    "eq": "РБК Санкт-Петербург"
  }
}

###
