POST {{base-url}}/api/v1/mediaplan
Content-Type: application/json

{
  "AdtList": {
    "AdtID": "700068653"
  },
  "ChannelList": {
    "Cnl": "1018578"
  },
  "EndMonth": "201904",
  "IncludeEmpty": "true",
  "SellingDirectionID": "23",
  "StartMonth": "201904"
}

###
