POST {{base-url}}/api/v1/program-breaks
Content-Type: application/json

{
  "SellingDirectionID": "23",
  "InclProgAttr": "0",
  "InclForecast": "0",
  "StartDate": "20190803",
  "EndDate": "20190803",
  "LightMode": "0",
  "CnlList": [
    {
      "Cnl": "1020313"
    }
  ],
  "ProtocolVersion": "2"
}

###
