name: Go

on:
  push:
    branches: [ actions ]
jobs:
  releases-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Swag
        run: go get github.com/swaggo/swag/cmd/swag
      - name: Http-swagger
        run: go get github.com/swaggo/http-swagger
      - name: Swagger template
        run: go get github.com/alecthomas/template
      - name: Swagger init
        run: swag init -g cmd/api/api-service.go
      - name: Tidy
        run: go mod tidy -compat=1.17
      - name: Testing
        run: go test -race -vet=off ./...
